### ISSUE TITLE
Cannot find module 'date-utils' 

### ISSUE THREAD

**Issue by samniu** [JerrySievert/date-utils#66]
when running a  node.js script require 'date-utils' module , it return error: 
```
➜  mobileapi git:(master) ✗ node server.js                       
module.js:471
    throw err;
    ^

Error: Cannot find module 'date-utils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/loginuser/workspace/node/node/mobileapi/server.js:3:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
➜  mobileapi git:(master) ✗ 
```

**Comment by JerrySievert** [comment]
are you absolutely sure you have date-utils installed?

try running `npm ls` and verifying that it is indeed installed.

if you post the results of the command, I'm happy to help diagnose.

**Comment by samniu** [comment]
First I used “npm install -g date-utils” command, will have this error.
and using “npm install date-utils” ,the problem is solved.
thanks !

```
➜  test git:(master) ✗ npm ls
node@1.0.0 /Users/loginuser/workspace/node
└── date-utils@1.2.21

➜  test git:(master) ✗ 
```
